### PR TITLE
Remove folly::is_trivially_copyable

### PR DESCRIPTION
**Pull request by JoeLoser**
Summary:
- There is no need for `folly::is_trivially_copyable` in
  `folly/Traits.h` since `std::is_trivially_copyable` ships with the
  standard library for GCC 5 and later.
- Previously, for GCC 4.9 and below, the symbol
  `std::is_trivially_copyable` was not present.
- Remove the CMake check for detecting presence of the symbol.

### CODE REVIEW

**Comment by yfeldblum** [comment]
While Folly no longer supports gcc49 as a whole and is documented (thanks!) that way, there are some internal cases which are still on gcc49 and which are using some undocumented subsets of Folly. So this PR can't be merged quite yet.

**Comment by yfeldblum** [comment]
I can't give specifics, but progress is being made. I want to bump to gcc5 also.

**Comment by JoeLoser** [comment]
Just rebased, fixed the recent `bitCast` utility to use `std::is_trivially_copyable`, and also removed the `#ifdef` for the `TriviallyCopyable` test in ExpectedTest. With this change, we expect any compiler we claim support for should have `std::is_trivially_copyable`, so we should enforce that with this test rather than only testing on Clang/GCC.

**Comment by JoeLoser** [comment]
I'll rebase again tonight as a703ff288c18f797aebd815d0cc7144bab473c21 landed with some usages of `folly::is_trivially_copyable` and we also have conflicts now in `Traits.h`.

**Comment by JoeLoser** [comment]
Rebased. Corresponding Thrift PR is here: https://github.com/facebook/fbthrift/pull/327

**Comment by yfeldblum** [comment]
Not as rapid progress as one might hope, unfortunately. I couldn't land this internally yet.

**Comment by JoeLoser** [comment]
Thanks for the update. I know you'll be happy only having to support gcc5 and later soon.

**Comment by JoeLoser** [comment]
Rebased and fixed conflicts. Any update on the progress of moving all of the internal projects off of GCC 4.9 so we can land this?

**Comment by JoeLoser** [comment]
Rebased with top of tree. Now that folly only supports GCC 5+, we should be able to land this safely, right?

**Comment by yfeldblum** [comment]
I hope so!

**Comment by yfeldblum** [comment]
Progress, but it looks like there are still cases internally of using clang with older libstdc++ which does not define `std::is_trivially_copyable`.

**Comment by JoeLoser** [comment]
Thanks for checking. We'll get there one day.

**Comment by yfeldblum** [comment]
This has now been done.

**Pull request closed without merging**
