### PR TITLE
Added Folly logo that makes look nicer

### PR DESCRIPTION
**Pull request by raihan71**
## Summary

* Added Folly logo in README.md that makes look nicer
* Changing width of the logo to smaller than before
* Added folder static/img for storing the logo in a better way and more accepted

## Test Plan

<strong>Before</strong>
image

<strong>After</strong>
image

### CODE REVIEW

**Comment by yfeldblum** [comment]
@LeeHowes Can we get the image published somewhere with a canonical URL?

**Comment by raihan71** [comment]
> @LeeHowes Can we get the image published somewhere with a canonical URL?

Oh yeah sure, wait I'll fix it

**Comment by raihan71** [comment]
> @LeeHowes Can we get the image published somewhere with a canonical URL?

Hey I just storing the logo to static/img folder, so let me know what you think? @yfeldblum

**Comment by raihan71** [comment]
> @LeeHowes Can we get the image published somewhere with a canonical URL?

Please update this PR, need what you think

**Comment by LeeHowes** [comment]
Sorry for the delay @raihan71 . I committed the SVG after some discussions, in the end roughly as you had proposed (but I had to do it slightly differently to work with our internal tools). I am landing the embedding in the readme separately as well to match the final location.

Thanks for the PR!

**Comment by raihan71** [comment]
> Sorry for the delay @raihan71 . I committed the SVG after some discussions, in the end roughly as you had proposed (but I had to do it slightly differently to work with our internal tools). I am landing the embedding in the readme separately as well to match the final location.
> 
> Thanks for the PR!

Ok cool resolved, thank you for the update

**Pull request closed without merging**
