### PR TITLE
Copyright, 2015 > 2016, for files A-D

### PR DESCRIPTION
**Pull request by siddharthasharma**
Updated copyright notices in the source from 2015 to 2016, for all files beginning from A to D.

### CODE REVIEW

**Comment by lbrandy** [comment]
Unfortunately, I think someone might have beaten you to this internally. I'll double check.

**Comment by siddharthasharma** [comment]
@lbrandy, what do you intend to state? I updated Haxl's notices last time and this time it's folly. Do double check, and update me. And, if you want A-Z, give me a day. L/F to response.

**Comment by Orvid** [comment]
@lbrandy I think the internal diff already landed and missed Folly completely, due to its use of a single year rather than range of years.

**Comment by Orvid** [comment]
Internal diff landed. See 321542683a01c3f334047531e9b487f047129775.

**Pull request closed without merging**
