### PR TITLE
Fixed up README files

### PR DESCRIPTION
**Pull request by sethkrasnianski**
There were a few README files that weren't saved with a markdown filetype. This prevented the github markdown parsing. Also:

- fixed a typo in the root README
- linked the root README to the `folly/docs/Overview` page
- wrapped commands and code in code blocks (root README & folly/wangle/rx README)

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sethkrasnianski** [comment]
Rebased.

**Comment by Gownta** [comment]
Looks good, except for the first line. The capital Y is intentional. I'll land this internally with that minor modification; this should show up on github next time we push.

**Comment by sethkrasnianski** [comment]
Cool, sounds good. So I know, what significance does the capital Y have?

**Comment by Gownta** [comment]
The capitalized letters spell "FOLY", which is the origin of "folly".

**Comment by sethkrasnianski** [comment]
Ahh neat... I didn't notice that :+1:

**Comment by Gownta** [comment]
@sethkrasnianski, our internal landing system clobbered your name in our git history and replaced it with mine. :/ I've commented on both commits, attributing them to you, but I'd also like to cross-reference them here:

https://github.com/facebook/folly/commit/0887b7ac672970bf401d58cb0bb828afb2df3854
https://github.com/facebook/folly/commit/513a1e16ffa3f235765cd8ecb2fe949bf0692e52

**Comment by sethkrasnianski** [comment]
:+1:

**Pull request closed without merging**
