### PR TITLE
Remove macro guards against GCC 4.9 code

### PR DESCRIPTION
**Pull request by JoeLoser**
Summary:
- Since folly requires GCC 5+ compiler, remove several macros which were
  guarding against when we supported GCC 4.9.

### CODE REVIEW

**Comment by yfeldblum** [comment]
What changed in the latest rev?

**Comment by JoeLoser** [comment]
Nothing changed other than a rebase.

**Comment by JoeLoser** [comment]
Any update on this @yfeldblum?

**Comment by yfeldblum** [comment]
Hey @JoeLoser, a few recent attempts to land this have been automatically blocked by possibly-spurious failed checks. I will try to land again though.

**Comment by JoeLoser** [comment]
@yfeldblum thanks for landing this.

**Pull request closed without merging**
