### PR TITLE
Check for overflow when growing Vectors.

### PR DESCRIPTION
**Pull request by SeanRBurton**
I don't know if this works, but it is at least in the spirit of the right idea.

### CODE REVIEW

**Comment by fredemmott** [comment]
Ping - we can't review or merge this without the CLA being completed.

**Comment by SeanRBurton** [comment]
Sorry, I've been busy.

**Comment by fredemmott** [comment]
Bot didn't link for some reason, review here: https://reviews.facebook.net/D47895

**Comment by JoeLoser** [comment]
Perhaps it's worth adding a test to verify this code path correctly throws `std::bad_alloc`? I know the code path looks innocent, but a test never hurts. :)

**Comment by yfeldblum** [comment]
This overall does not seem to be necessary.

**Pull request closed without merging**
