### PR TITLE
non x86_64 digits10 faster for all sizes

### PR DESCRIPTION
**Pull request by gbizzotto**

### CODE REVIEW

**Comment by gbizzotto** [comment]
`ARM7 rev4 (v71)` benchmark. I couldn't compile the whole folly+googletest+googlebenchmark+boost shebang on my raspberry pi, so i wrote a version of the test that uses only google benchmark.
```
----------------------------------------------------------------
Benchmark                      Time             CPU   Iterations
----------------------------------------------------------------
BM_digits10_1digit          5.02 ns         5.01 ns    138337072
BM_digits10_2_1digit        5.01 ns         5.01 ns    139424003

BM_digits10_2digit          5.02 ns         5.01 ns    138863629
BM_digits10_2_2digit        5.01 ns         5.01 ns    139185041

BM_digits10_3digit          5.84 ns         5.84 ns    119478773
BM_digits10_2_3digit        5.01 ns         5.01 ns    139237959

BM_digits10_4digit          5.01 ns         5.01 ns    139296264
BM_digits10_2_4digit        5.01 ns         5.01 ns    139223971

BM_digits10_5digit          76.0 ns         75.9 ns      9190479
BM_digits10_2_5digit        5.84 ns         5.84 ns    119524038

BM_digits10_6digit          88.5 ns         88.4 ns      7897237
BM_digits10_2_6digit        5.01 ns         5.01 ns    139368488

BM_digits10_7digit           107 ns          107 ns      6540445
BM_digits10_2_7digit        82.1 ns         82.1 ns      8498911

BM_digits10_8digit           139 ns          138 ns      5064865
BM_digits10_2_8digit         101 ns          101 ns      6974489

BM_digits10_9digit           253 ns          253 ns      2784908
BM_digits10_2_9digit         113 ns          113 ns      6174269

BM_digits10_10digit          275 ns          274 ns      2500847
BM_digits10_2_10digit        134 ns          134 ns      5182678

BM_digits10_11digit         99.3 ns         99.3 ns      7026433
BM_digits10_2_11digit       2.50 ns         2.50 ns    279448322

BM_digits10_12digit          136 ns          136 ns      5130597
BM_digits10_2_12digit       2.50 ns         2.50 ns    279266285

BM_digits10_13digit          180 ns          180 ns      3897195
BM_digits10_2_13digit        260 ns          260 ns      2710226

BM_digits10_14digit          229 ns          229 ns      3048641
BM_digits10_2_14digit        309 ns          309 ns      2260325

BM_digits10_15digit          317 ns          317 ns      2204857
BM_digits10_2_15digit        398 ns          398 ns      1747526

BM_digits10_16digit          370 ns          370 ns      1887114
BM_digits10_2_16digit        472 ns          471 ns      1489019

BM_digits10_17digit          464 ns          464 ns      1493191
BM_digits10_2_17digit        508 ns          507 ns      1367392

BM_digits10_18digit          580 ns          579 ns      1177496
BM_digits10_2_18digit        540 ns          540 ns      1281739

BM_digits10_19digit          634 ns          634 ns      1087749
BM_digits10_2_19digit        631 ns          631 ns      1083284

BM_digits10_20digit         5.84 ns         5.84 ns    119419110
BM_digits10_2_20digit       5.01 ns         5.01 ns    138931528
```

**Comment by nbronson** [comment]
Why is BM_digits10_2_11digit so good? Seems fishy

**Comment by gbizzotto** [comment]
Yeah, the input was not very good. I used random numbers and generated them as
```
    std::uint64_t size2 = std::pow(10, size-1);
    std::uint64_t result = size2 + rand64()%(9*size2);
```
But `rand()` is 32b so the input was like
```
10xxxxxxxxxx
100xxxxxxxxxx
1000xxxxxxxxxx
...
```
I fixed that and the results are more consistent.
```
----------------------------------------------------------------
Benchmark                      Time             CPU   Iterations
----------------------------------------------------------------
BM_digits10_1digit          11.8 ns         11.8 ns     59075468
BM_digits10_2_1digit        10.1 ns         10.1 ns     68759887

BM_digits10_2digit          5.06 ns         5.06 ns    137609043
BM_digits10_2_2digit        5.07 ns         5.06 ns    137562000

BM_digits10_3digit          5.06 ns         5.06 ns    137399570
BM_digits10_2_3digit        5.06 ns         5.06 ns    137699558

BM_digits10_4digit          5.06 ns         5.06 ns    137445237
BM_digits10_2_4digit        5.06 ns         5.06 ns    137636381

BM_digits10_5digit          5.06 ns         5.06 ns    137235842
BM_digits10_2_5digit        5.07 ns         5.06 ns    137673321

BM_digits10_6digit          5.06 ns         5.06 ns    137006828
BM_digits10_2_6digit        5.07 ns         5.06 ns    137430619

BM_digits10_7digit          5.06 ns         5.06 ns    137596646
BM_digits10_2_7digit        5.06 ns         5.06 ns    137597490

BM_digits10_8digit          5.07 ns         5.06 ns    137407297
BM_digits10_2_8digit        5.06 ns         5.06 ns    137622289

BM_digits10_9digit          5.06 ns         5.06 ns    137421346
BM_digits10_2_9digit        5.06 ns         5.06 ns    137540179

BM_digits10_10digit          223 ns          223 ns      3136250
BM_digits10_2_10digit       5.06 ns         5.06 ns    137637507

BM_digits10_11digit          256 ns          256 ns      2725573
BM_digits10_2_11digit       5.07 ns         5.06 ns    137713808

BM_digits10_12digit          306 ns          306 ns      2301176
BM_digits10_2_12digit       5.06 ns         5.06 ns    137727074

BM_digits10_13digit          498 ns          497 ns      1396889
BM_digits10_2_13digit        587 ns          586 ns      1189270

BM_digits10_14digit          573 ns          572 ns      1205451
BM_digits10_2_14digit        652 ns          652 ns      1067398

BM_digits10_15digit          725 ns          725 ns       958028
BM_digits10_2_15digit        890 ns          890 ns       785699

BM_digits10_16digit          859 ns          859 ns       812603
BM_digits10_2_16digit       1011 ns         1011 ns       686474

BM_digits10_17digit         1132 ns         1131 ns       614036
BM_digits10_2_17digit       1085 ns         1085 ns       640996

BM_digits10_18digit         1285 ns         1285 ns       542295
BM_digits10_2_18digit       1168 ns         1168 ns       597396

BM_digits10_19digit         1434 ns         1434 ns       488220
BM_digits10_2_19digit       1462 ns         1460 ns       478404

BM_digits10_20digit         2571 ns         2569 ns       272562
BM_digits10_2_20digit       1603 ns         1602 ns       435930
```

**Comment by gbizzotto** [comment]
Ok, I have fully unrolled that loop so now it's just comparisons and adds.

PROS:
Constant time.
Faster than or equal to the other solutions for all sizes for all sizes (ARM7: 5ns, see benchmark in previous comments)

CONS:
Bigger than the original solution (godbolt says 87 bytes vs 43), will use one more cache line
Still no match for the x86-64 hack

**Comment by yfeldblum** [comment]
I think something sufficiently like this exists in the `to_ascii` suite.

**Pull request closed without merging**
