### PR TITLE
Include MacOSX in TravisCI builds

### PR DESCRIPTION
**Pull request by calebmarchent**
Use homebrew bootstrap script for process; note nearly all the Travis
steps become conditional on os; so bit of shuffling was required to make
that work.

### CODE REVIEW

**Comment by calebmarchent** [comment]
Ok, test job ran; which is nice; always worth checking..

Next Steps;
1. Integrate with Joe’s stuff for the homebrew build
2. Run through test
3. Re-introduce the Linux build to Travis matrix

**Comment by JoeLoser** [comment]
Thanks for working on this. I'm happy to see that we'll be guarded with a CI build for Mac OS X rather than my local dev just breaking :)

**Comment by calebmarchent** [comment]
Seems to be building successfully, suffice we force weak symbols to be on.
Most recent tests seem to be running the MacOS build twice, this is not intentional; looks like an either os or the matrix sort of issue.

**Comment by calebmarchent** [comment]
Sort of looks like a viable, if not optimised solution now. 
Next Steps:
* Get Joe's PR merged.
* Re-create this change based on them.

**Comment by calebmarchent** [comment]
Now that Joe's change is landed; going to try and move this to a real PR.

**Comment by calebmarchent** [comment]
Going to abandon this PR, and create a new one for landing, hopefully avoiding weird "DO NOT MERGE" in the resulting title text

**Pull request closed without merging**
