### PR TITLE
Enable GroupVarint on Arm64

### PR DESCRIPTION
**Pull request by zhangkehong2brad**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by Orvid** [comment]
The bot just didn't comment that the CLA had been accepted.

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by Orvid** [comment]
-_-.....

**Pull request closed without merging**
