### PR TITLE
Branch-free versions of size() and c_str()

### PR DESCRIPTION
**Pull request by b-pass**
I saw @Gownta's talk on fbstring at cppcon '16 on Tuesday.  He mentioned that it was unfortunate that FBString has a branch in size() and c_str() because these are commonly called functions that we'd all like to be pretty fast.

So here's versions of those functions which don't branch.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are a Facebook employee, you can view this diff [on Phabricator](https://phabricator.intern.facebook.com/D3909502).

**Comment by Gownta** [comment]
We need to run some non-trivial performance tests on string code before we take in any optimizations. The branching is bad, but so is lengthier lists of assembly instructions. (godbolt assembly for this pattern: https://godbolt.org/g/sq29Qa)

I'll keep this diff in mind when we get gcc-5's comparison benchmarks up and running in production. Testing gcc-5 strings is the build team's first string-related priority. Once we've got those numbers, we'll start tuning fbstring.

Thanks for the taking an interest in fbstring code! I'm glad the talk got you interested in the code :)

**Comment by Orvid** [comment]
Also, this appears to have a few bugs somewhere, as it's causing a significant amount of tests to fail.

**Comment by b-pass** [comment]
Thanks @Orvid, I had a stupid typo in there.  Fixed it.

**Comment by Orvid** [comment]
We ended up going with a slightly different form to get the same results, see be4c6d6b3e21914df8a0207ef4f716a09a648745

**Pull request closed without merging**
