### PR TITLE
[clang-tidy] Use uppercase literals suffixes

### PR DESCRIPTION
**Pull request by neheb**
Found with hicpp-uppercase-literal-suffix

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by yfeldblum** [comment]
What's the problem with the lowercase suffixes?

**Comment by neheb** [comment]
It's a style issue mostly.

The given example is differentiating 1 vs l. See: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152241

**Comment by yfeldblum** [comment]
This PR includes only changes from `u` to `U`, which seems not to be a problem. The `u` seems generally useful with `auto` because of size-conversion warnings, while `l` or `ll` by themselves seem not useful in general because widening is typically not a problem.

**Comment by neheb** [comment]
Hrm fair enough.

**Pull request closed without merging**
