### PR TITLE
Fix typo in docs/Function.md

### PR DESCRIPTION
**Pull request by pravic**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/961936840589790/int_phab) to review.

**Comment by elliottneilclark** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/961936840589790/int_phab) to review.

**Pull request closed without merging**
