### PR TITLE
Fixing typo in Readme

### PR DESCRIPTION
**Pull request by vertexodessa**

### CODE REVIEW

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by elliottneilclark** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1714590825465218/int_phab) to review.

**Pull request closed without merging**
