### PR TITLE
#1817 Fix openssl include as OpenSSL for case sensitive file systems.

### PR DESCRIPTION
**Pull request by Romick2005**
This should solve the issue for case sensitive file systems.

### CODE REVIEW

**Comment by Orvid** [comment]
As far as I can tell, the official casing is lowercase: https://github.com/openssl/openssl/tree/master/include/openssl

What is providing this in mixed case?

**Comment by Orvid** [comment]
The casing there seems to be the result of a non-standard casing being provided by those packages, so we can't go changing them here.

The couple of linux distros I checked, upstream openssl, and vcpkg all have the directory name as lowercase, so that's what we want to keep here.

The correct fix is to update the casing used in https://github.com/krzyzanowskim/OpenSSL to match with what is already used elsewhere.

**Comment by Romick2005** [comment]
But does the change break anything on your side? I think that it actually fix. Can you please confirm that this pull request does not work for you. Thank you.

**Comment by Orvid** [comment]
This change should break the build on linux, since the default file system is case sensitive, but I'll kick off the builds to verify.

**Comment by Orvid** [comment]
This does appear to break the linux build.

**Comment by Romick2005** [comment]
Great thank you! Can you please then merge my changes? In order to fix issues for case sensitive file systems. Thank you for the check!

**Pull request closed without merging**
