### PR TITLE
Use boost::has_less instead of rolling our own

### PR DESCRIPTION
**Pull request by JoeLoser**
Summary:
- An internal type trait, `HasLess` is used to detect if there exists an
  `operator<` such that `T < U` is well-formed.
- This type trait is not needed with recent versions of Boost which has
  this exact type trait: `boost::has_less`.
- Since we rely on Boost 1.55 or later which does contain this symbol,
  just use that.

Note:
- A future commit will change `notThereYet` to use the `#if 0`
  implementation now that we are on Boost 1.46 or later.

### CODE REVIEW

**Comment by JoeLoser** [comment]
@yfeldblum anything I can do to help get this landed?

**Comment by lbrandy** [comment]
This was blocked on internal review. I just accepted it...

**Comment by JoeLoser** [comment]
Thanks for the review, @lbrandy 👍

**Comment by yfeldblum** [comment]
Thanks for flagging this.

Note that I just removed `HasLess` in ff5f718ecab5dd2de75045097f06aa61aad513a3 and f2c0cfdd576c08f1e0217079cba79bc0e4c12312.

**Pull request closed without merging**
