### PR TITLE
Remove dependency from boost class noncopyable

### PR DESCRIPTION
**Pull request by brunomorishita**
With explicitly deleted member functions in C++11 the boost class noncopyable is not needed anymore

### CODE REVIEW

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/829601010508145/int_phab) to review.

**Comment by elliottneilclark** [comment]
LockFreeRingBuffer is non-copyable, however Cursor inside of it is copyable. This change breaks LockFreeRingBufferTest.

**Comment by yfeldblum** [comment]
PR was deleted.

**Pull request closed without merging**
