### PR TITLE
TravisCI build for Folly on MacOS

### PR DESCRIPTION
**Pull request by calebmarchent**
Use homebrew bootstrap script for process; note nearly all the Travis
steps become conditional on os; so bit of shuffling was required to make
that work.

### CODE REVIEW

**Comment by JoeLoser** [comment]
Thanks for working on this @calebmarchent.

**Comment by JoeLoser** [comment]
@calebmarchent one thing to keep in mind is that the existing bootstrap script for Mac *does not* run the tests. We should probably pass `-DBUILD_TESTS=ON` when invoking this script for CI purposes.

**Comment by JoeLoser** [comment]
Any update on this, @calebmarchent? How do others internally feel about this work?

**Comment by calebmarchent** [comment]
It did get held at internal review, then I got onto something else, now I need to finish some stuff this week; but next week should be clearer so will tackle at start of next week.

**Comment by calebmarchent** [comment]
Rebased; because it has been a while; will revise on next step.

**Comment by calebmarchent** [comment]
Update: Have implemented the first code review feedback; splitting out enable of IPv6 in docker.
But found the travis config is shared with a number of oss projects; which means I will need to split out the config before enabling OSX build; which I will do for folly only.

**Comment by Orvid** [comment]
We've dropped support for Travis in favor of Github Actions, which already has MacOS support.

**Pull request closed without merging**
