### PR TITLE
fix: add missing boost include required for BOOST_PP_IF

### PR DESCRIPTION
**Pull request by mhx**

### CODE REVIEW

**Comment by luislobo** [comment]
Watchman is failing I think because of this:
```
/repos/github.com-facebook-folly.git/folly/io/async/AsyncSocket.cpp:3783:9: error: ‘tmpVec’ was not declared in this scope
 3783 |         tmpVec,
      |         ^~~~~~
[11/152] Building CXX object CMakeFiles/folly_base.dir/folly/io/async/Request.cpp.o
```

**Comment by Orvid** [comment]
I just need a stamp on the internal Diff and then I can land this and get things building again.

This was caused by some automated tooling not realizing that this include was in-fact used.

**Comment by luislobo** [comment]
I just tested it modifying the temporary clone watchman creates and it did continue, but now erroring on:

```
/tmp/fbcode_builder_getdeps-ZhomeZluis.lobo@epicio.comZDownloadsZwatchman-2024.05.13.00ZbuildZfbcode_builder/repos/github.com-facebook-folly.git/folly/FBString.h:444:20: error: ‘category’ was not declared in this scope
  444 |     ptr = (category() == Category::isSmall) ? small_ : ptr;
      |            ~~~~~~~~^~
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZluis.lobo@epicio.comZDownloadsZwatchman-2024.05.13.00ZbuildZfbcode_builder/build/folly', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '6']' returned non-zero exit status 1.
!! Failed
```
is it related?

**Comment by Orvid** [comment]
Looks like I was too slow in landing the internal version of this, so someone else landed a6925ca30f6f9b9531cad5b09fad278083b901d3, which does the same thing as this fix.

**Pull request closed without merging**
