### PR TITLE
Fixed README download link to get the correct GTest version

### PR DESCRIPTION
**Pull request by mtodat**

### CODE REVIEW

**Comment by lbrandy** [comment]
Do we actually require gtest 1.7?

**Comment by andrewcox** [comment]
Yes
https://github.com/facebook/folly/blob/master/folly/test/Makefile.am#L20

**Comment by loverszhaokai** [comment]
Yes, the gtest-1.7.0 is required!

**Comment by Gownta** [comment]
We've landed this internally. @mtodat: I realize now that I derped up the git commands; the commit shows up as being authored by me instead of you :(. I've commented on the github diff to attribute the change to you.

**Comment by mtodat** [comment]
Hi @Gownta, don't worry about this. Thank you for mentioning me in the change :)

**Pull request closed without merging**
