### PR TITLE
AcceptCallback disallow undeclared copy and move, but allow default ctor

### PR DESCRIPTION
**Pull request by cppfool**
AcceptCallback disallow undeclared copy construction, copy assignment,

move construction, move assignment. But it allow implicit default

construction.

Test Plan: all folly/tests, make check for 37 tests, passed.

### CODE REVIEW

**Comment by chipturner** [comment]
Hello, thank you for your patch (and the others, which I am in the process of merging).  Can you offer a little more context on this diff?  Why only partially disabling value semantics?

**Comment by cppfool** [comment]
@chipturner, Classes which inherits from AcceptCallback need
default constructor but others.
At least not yet.

**Comment by cppfool** [comment]
@chipturner, We're =deleteing move assign here. But we're not explicitely =deleteing other
value semantics enablers. By asking "only partially disabling value semantics" are
you targeting previous two sentences?

**Comment by Gownta** [comment]
Unless it offers a concrete benefit, we should not be marking functions as deleted.

**Pull request closed without merging**
